#on: [push]
on:
  # Trigger the workflow on push or pull request
  pull_request:
    branches:
      - master
      - develop

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      #- uses: actions/checkout@v4
      #- id: foo
      #  uses: CraigWetzelberger/hello-world-composite-action/subdir@main
      #  with:
      #    who-to-greet: 'Mona the Octocat'
      #- run: echo random-number "$RANDOM_NUMBER"
      #  shell: bash
      #  env:
      #    RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
      #- uses: actions/checkout@v4
      #
      # Works:
      #- uses: CraigWetzelberger/hello-world-composite-action/example@main
      #
      #
      #
      - uses: CraigWetzelberger/hello-world-composite-action/excomment@main
        with:
          github_access_token:  ${{ secrets.GITHUB_TOKEN }}

